platzigram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include(('posts.urls', 'posts'), namespace='posts')),

    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLs"""

# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [
    path(
        route='',
        view=views.PostsFeedView.as_view(),
        name='feed'),
    path(
        route='posts/new/',
        view=views.PostCreateView.as_view(),
        name='create'
    ),
    path(
        route='posts/<int:pk>',
        view=views.PostsDetailView.as_view(),
        name='detail'
    ),
]

users/urls.py
"""Users URLs"""
# Django
from django.urls import path

# Views
from users import views

urlpatterns = [
    # Management
    path(
        route='login/',
        view=views.UserLoginView.as_view(),
        name='login'
    ),

    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.UserSignUp.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UserUpdate.as_view(),
        name='update'
    ),

    path(
        route='follow/<str:username>',
        view=views.follow_view,
        name='follow'
    ),

    path(
        route='unfollow/<str:username>',
        view=views.unfollow_view,
        name='unfollow'
    ),

    # Posts
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

users/models.py
""" Users models """
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    """Profile model
    Proxy model that extends the base data with other information
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    relationships = models.ManyToManyField(
        'self',
        through='Follower',
        symmetrical=False,
        related_name='followers'
    )

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(upload_to='users/pictures', blank=True, null=True)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def add_follower(self, profile):
        relationship, created = Follower.objects.get_or_create(
            profile_from=self,
            profile_to=profile)
        return relationship

    def remove_relationship(self, person):
        Follower.objects.filter(
            profile_from=self,
            profile_to=person).delete()
        return

    def get_relationships(self):
        return self.relationships.filter(
            to_profile__profile_from=self)

    def get_related_to(self):
        return self.followers.filter(
            from_profile__profile_to=self)

    def get_following(self):
        return self.get_relationships()

    def get_followers(self):
        return self.get_related_to()


class Follower(models.Model):
    profile_from = models.ForeignKey(Profile, related_name='from_profile', on_delete=models.DO_NOTHING)
    profile_to = models.ForeignKey(Profile, related_name='to_profile', on_delete=models.DO_NOTHING)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)

users/forms.py
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Signup form"""
    username = forms.CharField(min_length=4, max_length=200)

    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(min_length=6, widget=forms.EmailInput())

    def clean_username(self):
        """User name must be unique"""
        username = self.cleaned_data["username"]
        username_exists = User.objects.filter(username=username).exists()

        if username_exists:
            raise forms.ValidationError('Username {0} is al ready in use'.format(username))
        return username

    def clean(self):
        """Verify password and confirmation match"""
        data = super().clean()
        password = data['password']
        confirmation = data['password_confirmation']
        if password != confirmation:
            raise forms.ValidationError('Passwords does not match')

        return data

    def save(self):
        """ Create user and profile """
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
""" User views. """

# Django
from django.contrib.auth import views as auth_views
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

# Forms
from users.forms import SignupForm

# Models
from posts.models import Post
from users.models import Profile
from django.contrib.auth.models import User

import json

class UserLoginView(auth_views.LoginView):
    """Login view"""
    template_name = 'users/login.html'


class UserDetailView(LoginRequiredMixin, DetailView):
    """User detail view."""
    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        """Add user's posts to context"""
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context['following'] = user.profile.get_following().count()
        context['followers'] = user.profile.get_followers().count()
        context['posts'] = Post.objects.filter(user=user).order_by('-created')

        return context


class UserSignUp(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class UserUpdate(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self, queryset=None):
        """Returns user's profile"""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile"""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    template_name = 'users/logout.html'


@login_required()
def logout_view(request):
    """Logout a user"""
    logout(request)
    return redirect(reverse('users:login'))


@login_required()
def follow_view(request, username):
    if request.method == 'GET':
        request.user.profile.add_follower(User.objects.get(username=username).profile)
        return redirect(reverse('users:detail', kwargs={'username': username}))


@login_required()
def unfollow_view(request, username):

    if request.method == 'GET':
        print("it's working")
        request.user.profile.remove_relationship(User.objects.get(username=username).profile)
        return redirect(reverse('users:detail', kwargs={'username': username}))

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
</head>
<body class="h-100">
    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <img src="{% static 'img/instagram.png' %}" class="img-fluid rounded mx-auto d-block pb-4" style="max-width: 60%;">
                {% block container %}{% endblock%}
            </div>
        </div>
    </div>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ user.username }} | Profile</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img
                    src="{{ user.profile.picture.url }}"
                    alt="@{{ user.username }}"
                    class="rounded-circle" width="150px" height="150px"/>
            </div>
            <div class="col-sm-8">
                <div class="row">
                    <div class="col-sm-4">
                        <h2 style="font-weight: 100;">
                            @{{ user.username }}
                        </h2>
                    </div>
                    <div class="col-sm-8 mt-1">
                        {% if user == request.user %}
                            <a href="{% url 'users:update' %}"
                               class="btn btn-sm btn-outline-info">
                                    Edit profile
                            </a>
                        {% elif request.user.profile in user.profile.get_followers %}
                            <a href="{% url 'users:unfollow' user.username %}"
                               class="btn btn-sm btn-danger">
                                    Unfollow
                            </a>
                        {% else %}
                            <a href="{% url 'users:follow' user.username %}"
                               class="btn btn-sm btn-primary">
                                    Follow
                            </a>
                        {% endif %}
                    </div>

                </div>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ posts.count }}</b> posts
                    </div>
                    <div class="col-sm-4">
                        {% if followers > 0 %}
                            <b>{{ followers }}</b>
                        {% else %}
                            <b>0</b>
                        {% endif %}
                        followers
                    </div>
                    <div class="col-sm-4">
                        {% if following > 0 %}
                            <b>{{ following }}</b>
                        {% else %}
                            <b>0</b>
                        {% endif %}
                        following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.biography }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>

    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.id %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

<script>
function vote(kind) {
  $.getJSON("/vote/", { pk:{{ object.pk }}, vote: kind }, function(json){
    alert("Was successful?: " + json['success']);
  });
}
function addClickHandlers() {
  $("#upvote").click( function() { vote("up") });
  $("#downvote").click( function() { vote("down") });
}
$(document).ready(addClickHandlers);
</script>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram Login</title>
{% endblock %}

{% block container %}
    {% if form.errors %}
        <p class="alert alert-danger">Your username and password didn't match</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" name="username" placeholder="Username" type="text" required="true">
        </div>
        <div class="form-group">
            <input class="form-control" name="password" placeholder="Password" type="password" required="true">
        </div>

        <button class="btn btn-primary btn-block mt-4" type="submit">
            Sign in!
        </button>

        <p class="mt-4">Don't have an account yet? <a href="{% url 'users:signup' %}">Sign up here.</a> </p>

    </form>

{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for message in messages %}
                    <p class="alert alert-success">{{ message }}</p>
                {% endfor %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                <div class="alert alert-danger">
                    <b>Picture: </b> {{ error }}
                </div>
                {% endfor %}

                <hr><br>

                {# Website field #}
                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                        type="url"
                        name="website"
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                {# Biography #}
                <div class="form-group">
                    <label>Biography</label>
                    <textarea
                            class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                            name="biography"
                    >{%if form.errors%}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}